### PR TITLE
ENH: Update ALPACA module for compatibility with ITK 5.4 and SlicerANTs

### PR DESCRIPTION
**Pull request by jcfr**
This commit updates the ALPACA module to support use alongside the `itk-ants` package, which requires ITK 5.4 and is installed via the ITKANTsCommon module provided by the SlicerANTs extension.

The ALPACA module now requires the following packages:
- itk `>= 5.4.0, == 5.4.*`
- itk-fpfh `>= 0.2.0, == 0.2.*`
- itk-ransac `>= 0.2.1, == 0.2.*`

This pull request is expected to fix the following issue:
* https://github.com/Slicer/Slicer/issues/7789

### CODE REVIEW

**Comment by jcfr** [comment]
@muratmaga Could test that the ALPACA workflow works as expected with the proposed change ?

@thewtex While I expect this to work when the extension is used in the context of Slicer Preview depending on ITK 5.4, do you anticipate any issue installing ITK 5.4 python packages along side ITK 5.3 used in the last Slicer Stable version ?

**Comment by muratmaga** [comment]
> @muratmaga Could test that the ALPACA workflow works as expected with the proposed change ?
> 
I will try, but wouldn't this break the functionality in the current stable? Can it work with itk 5.4?

**Comment by muratmaga** [comment]
> @muratmaga Could test that the ALPACA workflow works as expected with the proposed change ?
> 
> @thewtex While I expect this to work when the extension is used in the context of Slicer Preview depending on ITK 5.4, do you anticipate any issue installing ITK 5.4 python packages along side ITK 5.3 used in the last Slicer Stable version ?

Tested on today's preview on Mac.
1. If I install SlicerANTs and run and then ALPACA, this change has no effect I get the same error message as before, which is 

```
[DEBUG][Qt] 20.06.2024 11:06:59 [] (unknown:0) - Switch to module:  "ALPACA"
[CRITICAL][Stream] 20.06.2024 11:06:59 [] (unknown:0) - Traceback (most recent call last):
[CRITICAL][Stream] 20.06.2024 11:06:59 [] (unknown:0) -   File "/Users/amaga/jcfr/SlicerMorph/ALPACA/ALPACA.py", line 105, in setup
[CRITICAL][Stream] 20.06.2024 11:06:59 [] (unknown:0) -     from itk import Fpfh
[CRITICAL][Stream] 20.06.2024 11:06:59 [] (unknown:0) - ImportError: cannot import name 'Fpfh' from 'itk' (/Users/amaga/Desktop/Slicer.app/Contents/lib/Python/lib/python3.9/site-packages/itk/__init__.py)
[DEBUG][Qt] 20.06.2024 11:08:16 [] (unknown:0) - Switch to module:  ""
```

2. If I install and run ALPACA in a new installation, it works and does bring itk 5.4. However, when I try to add SlicerANTs and try to use the registration, this is the error:
```
[Qt] Populating font family aliases took 121 ms. Replace uses of missing font family ".AppleSystemUIFont" with one that exists to avoid this cost. 
Passing Slicer nodes to ITK filters is not yet implemented
Traceback (most recent call last):
  File "/Users/amaga/SlicerANTs/ANTsRegistration/ANTsRegistration.py", line 717, in onRunRegistrationButton
    self.logic.process(**parameters)
  File "/Users/amaga/SlicerANTs/ANTsRegistration/ANTsRegistration.py", line 962, in process
    ants_reg = itk.ANTSRegistration[type(fixedImage), type(movingImage), precision_type].New()
  File "/Users/amaga/Desktop/Slicer.app/Contents/lib/Python/lib/python3.9/site-packages/itk/support/lazy.py", line 131, in __getattribute__
    value = types.ModuleType.__getattribute__(self, attr)
AttributeError: module 'itk' has no attribute 'ANTSRegistration'
```

**Comment by thewtex** [comment]
> do you anticipate any issue installing ITK 5.4 python packages along side ITK 5.3 used in the last Slicer Stable version ?

I do not anticipate an issue, but I would not be too surprised if we discover the impact of an unknown, missing name-mangled symbol.

**Comment by thewtex** [comment]
> 2\. If I install and run ALPACA in a new installation, it works and does bring itk 5.4. However, when I try to add SlicerANTs and try to use the registration, this is the error:

May be addressed by: https://github.com/SlicerMorph/SlicerANTs/pull/9

**Comment by muratmaga** [comment]
> > 2. If I install and run ALPACA in a new installation, it works and does bring itk 5.4. However, when I try to add SlicerANTs and try to use the registration, this is the error:
> 
> May be addressed by: [SlicerMorph/SlicerANTs#9](https://github.com/SlicerMorph/SlicerANTs/pull/9)

OK. I tried with your branch (i was testing wrong one) and while it does try to bring ITK, it still fails with this errror:
```
Collecting itk-ants>=0.6.0
  Downloading itk_ants-0.6.0-cp39-cp39-macosx_10_9_x86_64.whl.metadata (15 kB)
Requirement already satisfied: itk==5.4.* in /Users/amaga/Desktop/Slicer.app/Contents/lib/Python/lib/python3.9/site-packages (from itk-ants>=0.6.0) (5.4.0)
Requirement already satisfied: itk-core==5.4.0 in /Users/amaga/Desktop/Slicer.app/Contents/lib/Python/lib/python3.9/site-packages (from itk==5.4.*->itk-ants>=0.6.0) (5.4.0)
Requirement already satisfied: itk-numerics==5.4.0 in /Users/amaga/Desktop/Slicer.app/Contents/lib/Python/lib/python3.9/site-packages (from itk==5.4.*->itk-ants>=0.6.0) (5.4.0)
Requirement already satisfied: itk-io==5.4.0 in /Users/amaga/Desktop/Slicer.app/Contents/lib/Python/lib/python3.9/site-packages (from itk==5.4.*->itk-ants>=0.6.0) (5.4.0)
Requirement already satisfied: itk-filtering==5.4.0 in /Users/amaga/Desktop/Slicer.app/Contents/lib/Python/lib/python3.9/site-packages (from itk==5.4.*->itk-ants>=0.6.0) (5.4.0)
Requirement already satisfied: itk-registration==5.4.0 in /Users/amaga/Desktop/Slicer.app/Contents/lib/Python/lib/python3.9/site-packages (from itk==5.4.*->itk-ants>=0.6.0) (5.4.0)
Requirement already satisfied: itk-segmentation==5.4.0 in /Users/amaga/Desktop/Slicer.app/Contents/lib/Python/lib/python3.9/site-packages (from itk==5.4.*->itk-ants>=0.6.0) (5.4.0)
Requirement already satisfied: numpy in /Users/amaga/Desktop/Slicer.app/Contents/lib/Python/lib/python3.9/site-packages (from itk==5.4.*->itk-ants>=0.6.0) (1.26.4)
Downloading itk_ants-0.6.0-cp39-cp39-macosx_10_9_x86_64.whl (10.0 MB)

Installing collected packages: itk-ants
Successfully installed itk-ants-0.6.0
Passing Slicer nodes to ITK filters is not yet implemented
Traceback (most recent call last):
  File "/Users/amaga/thewtex/SlicerANTs/ANTsRegistration/ANTsRegistration.py", line 717, in onRunRegistrationButton
    self.logic.process(**parameters)
  File "/Users/amaga/thewtex/SlicerANTs/ANTsRegistration/ANTsRegistration.py", line 962, in process
    ants_reg = itk.ANTSRegistration[type(fixedImage), type(movingImage), precision_type].New()
  File "/Users/amaga/Desktop/Slicer.app/Contents/lib/Python/lib/python3.9/site-packages/itk/support/lazy.py", line 131, in __getattribute__
    value = types.ModuleType.__getattribute__(self, attr)
AttributeError: module 'itk' has no attribute 'ANTSRegistration'
```

**Comment by muratmaga** [comment]
@jcfr @smrolfe this seems to work and I want to merge this. However, I am not sure what's happening, since the current ALPACA has this UI (notice the wording in Scaling and Projection, and both being enabled). 

image

versus UI of JC's branch has the older and more confusing terminology:

image

Not sure why git is not showing this as a conflict. It says it is ready to merge and I worried about overwriting this change. Can someone with more git knowledge look into this?

**Comment by thewtex** [comment]
@muratmaga thanks for testing! If Slicer is restarted, does it work?

**Comment by jcfr** [comment]
I just rebased the branch on top of the current master

> git is not showing this as a conflict

Since the updated files have not been updated recently, there were no conflicts.

**Comment by muratmaga** [comment]
All seems good now.
